### ISSUE TITLE
Where to add license info? (OMTD-SHARE 2.0.0)

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-share_metadata_schema#2]
When I search in https://openminted.github.io/releases/omtd-share/2.0.0/ I find a "rightsInfo" element, but at least using text-search (CTRL-F) in the browser, I cannot find out where "rightsInfo" is actually referenced - i.e. which element can have a "rightsInfo" child.

**Comment by pennyl67** [comment]
It's in the componentDistributionInfo; child elements are in the diagram, and this is why the text-search can't help. I can generate again the documentation, if you want, so that child elements also appear in the text box, but the documentation is already huge enough.
One thing that might also help is generating a sample xml file for components; would that help you?

**Comment by reckart** [comment]
Well, I am working with the Java classes generated from the XSDs and provided by omtd-share-api. So I am using the API to construct a description in memory and then write it to XML so that I can see what it actually looks like. That helps quite a bit. 

I think generating the documentation in such a way that the names captured in the images is also available as text might be useful. I can partially use Eclipse to figure out which elements are used where, but not in all cases.

**Comment by pennyl67** [comment]
Ok, I'll do so and generate also sample XML files directly from the XSD.
