### ISSUE TITLE
ParameterInfo too verbose

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-share_metadata_schema#3]
It seems to me that the ParameterInfo type is too verbose:

```
        ParameterInfo parameterInfo = new ParameterInfo();
        parameterInfo.setParameterName(value);
        parameterInfo.setParameterLabel(value);
        parameterInfo.setParameterDescription(value);
        ...
```

Wouldn't simple element names suffice?

```
        ParameterInfo parameterInfo = new ParameterInfo();
        parameterInfo.setName(value);
        parameterInfo.setLabel(value);
        parameterInfo.setDescription(value);
        ...
```

**Comment by pennyl67** [comment]
It's a classic case of whether one should use the same element/property irrespective of which element it modifies or whether it should be differentiated: e.g. use "name" for resource names, person names, licence names, parameter names etc. There are pros and cons against both options; I try to differentiate because it makes queries easier and the metadata elements more transparent.

**Comment by reckart** [comment]
Well, ok. I think I would prefer the strategy of using the shorter names.
